steps:
- name: 'gcr.io/k8s-skaffold/skaffold'
  id: build-and-test
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    # Build and push images
    cd web-app && skaffold build --interactive=false \
    --file-output artifacts.json \
    --default-repo us-central1-docker.pkg.dev/akshay-cicd-demo/flutter-frontend \
    && cd ..
               
- name: 'google/cloud-sdk:latest'
  id: create-release
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set deploy/region us-central1
    gcloud alpha deploy apply --file clouddeploy-config/target-test.yaml
    gcloud alpha deploy apply --file clouddeploy-config/target-staging.yaml
    gcloud alpha deploy apply --file clouddeploy-config/target-prod.yaml
    gcloud alpha deploy releases create $SHORT_SHA-$(date +%s) \
                        --delivery-pipeline flutter-app \
                        --description "$(git log -1  --pretty='%s')" \
                        --region us-central1 \
                        --build-artifacts web-app/artifacts.json
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-flutter-cicd-artifacts/'
    paths:
    - '/workspace/web-app/artifacts.json'
options:
  machineType: E2_HIGHCPU_8
timeout: 3600s

