steps:
- name: 'gcr.io/k8s-skaffold/skaffold'
  id: build-and-test
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    # Build and push images
    cd web-app && skaffold build --interactive=false \
    --file-output artifacts.json \
    --default-repo us-central1-docker.pkg.dev/akshay-cicd-demo/flutter-frontend \
    && cd ..
               
- name: 'google/cloud-sdk:latest'
  id: create-release
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud alpha deploy apply --file clouddeploy-config/target-test.yaml --region us-central1
    gcloud alpha deploy apply --file clouddeploy-config/target-staging.yaml --region us-central1
    gcloud alpha deploy apply --file clouddeploy-config/target-prod.yaml --region us-central1
    gcloud alpha deploy releases create $SHORT_SHA-$(date +%Y-%m-%d) \
                        --delivery-pipeline flutter-app \
                        --description "$(git log -1  --pretty='%s')" \
                        --region us-central1 \
                        --build-artifacts web-app/artifacts.json \
                        --source web-app/

