apiVersion: v1
kind: Service
metadata:
  name: flutter-frontend
  labels: 
    app: flutter-frontend
spec:
  selector:
    app: flutter-frontend
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-frontend
  labels:
    app: flutter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter-frontend
  template:
    metadata:
      labels:
        app: flutter-frontend
    spec:
      containers:
      - name: flutter-frontend
        image: flutter-frontend
        ports:
        - containerPort: 8080
